/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bpvfhbpugsxbuvgnqxpi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwdmZoYnB1Z3N4YnV2Z25xeHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2NTc0OTUsImV4cCI6MjA4NjIzMzQ5NX0.ptGU7jfPGjtjOOalucTlpJ6I-bQR9NAHsxq6d-vqdeA"